name: Sanity Check

description: Sanity Check of MetricsHub

runs:
  using: composite

  steps:

    - name: List all files
      if: runner.os == 'Linux'
      run: ls -al
      shell: bash

    - uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install Dependencies
      if: runner.os == 'Linux'
      run: pip install -r requirements.txt
      shell: bash

