name: Sanity Check

description: Sanity Check of MetricsHub

runs:
  using: composite

  steps:

    - name: List all files
      if: runner.os == 'Linux'
      run: ls -al
      shell: bash

    - name: List all action files
      if: runner.os == 'Linux'
      run: ls -al ${{ github.action_path}}
      shell: bash

    - name: Install Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version-file: ${{ github.action_path }}/.python-version

    - name: Install Dependencies
      if: runner.os == 'Linux'
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

